import type { Metadata } from "next";
import "./globals.css";
import { Libertinus_Sans } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import { ThemeProvider } from "@/components/ui/theme-provider";

const libertinus = Libertinus_Sans({
  weight: ["400", "700"],
  style : [ "italic"],
  subsets: ["latin"],
  variable: "--font-libertinus",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${libertinus.variable} font-sans`}>
     <AuthProvider>
     <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
     </AuthProvider>
      </body>
    </html>
  );
}
